before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    # The different architectures that Vault supports
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
    binary: 'vvw'
archives:
  - format: 'tar.gz'
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - docs/**/*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  draft: true
changelog:
  skip: true
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}_src'
