before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    # The different architectures that Vault supports
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
    binary: '{{ .ProjectName }}_{{ .Version }}'
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  draft: true
changelog:
  skip: true