// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	hcl "github.com/hashicorp/hcl/v2"

	mock "github.com/stretchr/testify/mock"

	plugins "github.com/opencredo/venafi-vault-wizard/app/plugins"
)

// PluginImplConstructor is an autogenerated mock type for the PluginImplConstructor type
type PluginImplConstructor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *PluginImplConstructor) Execute(_a0 *plugins.Plugin, _a1 *hcl.EvalContext) (plugins.PluginImpl, error) {
	ret := _m.Called(_a0, _a1)

	var r0 plugins.PluginImpl
	if rf, ok := ret.Get(0).(func(*plugins.Plugin, *hcl.EvalContext) plugins.PluginImpl); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugins.PluginImpl)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*plugins.Plugin, *hcl.EvalContext) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
