// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	plugins "github.com/opencredo/venafi-vault-wizard/app/plugins"
	mock "github.com/stretchr/testify/mock"
)

// PluginImplConstructor is an autogenerated mock type for the PluginImplConstructor type
type PluginImplConstructor struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *PluginImplConstructor) Execute() plugins.Plugin {
	ret := _m.Called()

	var r0 plugins.Plugin
	if rf, ok := ret.Get(0).(func() plugins.Plugin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugins.Plugin)
		}
	}

	return r0
}
