// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Check is an autogenerated mock type for the Check type
type Check struct {
	mock.Mock
}

// Error provides a mock function with given fields: message
func (_m *Check) Error(message string) {
	_m.Called(message)
}

// Success provides a mock function with given fields: message
func (_m *Check) Success(message string) {
	_m.Called(message)
}

// UpdateStatus provides a mock function with given fields: status
func (_m *Check) UpdateStatus(status string) {
	_m.Called(status)
}

// Warning provides a mock function with given fields: message
func (_m *Check) Warning(message string) {
	_m.Called(message)
}
