// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	reporter "github.com/opencredo/venafi-vault-wizard/app/reporter"
	mock "github.com/stretchr/testify/mock"
)

// Section is an autogenerated mock type for the Section type
type Section struct {
	mock.Mock
}

// AddCheck provides a mock function with given fields: name
func (_m *Section) AddCheck(name string) reporter.Check {
	ret := _m.Called(name)

	var r0 reporter.Check
	if rf, ok := ret.Get(0).(func(string) reporter.Check); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reporter.Check)
		}
	}

	return r0
}

// Info provides a mock function with given fields: message
func (_m *Section) Info(message string) {
	_m.Called(message)
}
