// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// VaultSSHClient is an autogenerated mock type for the VaultSSHClient type
type VaultSSHClient struct {
	mock.Mock
}

// AddIPCLockCapabilityToFile provides a mock function with given fields: filename
func (_m *VaultSSHClient) AddIPCLockCapabilityToFile(filename string) error {
	ret := _m.Called(filename)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *VaultSSHClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteFile provides a mock function with given fields: sourceFile, hostDestination
func (_m *VaultSSHClient) WriteFile(sourceFile io.Reader, hostDestination string) error {
	ret := _m.Called(sourceFile, hostDestination)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, string) error); ok {
		r0 = rf(sourceFile, hostDestination)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
