// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VenafiConnectionConfig is an autogenerated mock type for the VenafiConnectionConfig type
type VenafiConnectionConfig struct {
	mock.Mock
}

// GetAsMap provides a mock function with given fields:
func (_m *VenafiConnectionConfig) GetAsMap() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}
