// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	plugins "github.com/opencredo/venafi-vault-wizard/app/plugins"
	mock "github.com/stretchr/testify/mock"
)

// pluginImplConstructor is an autogenerated mock type for the pluginImplConstructor type
type pluginImplConstructor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *pluginImplConstructor) Execute(_a0 *plugins.Plugin) plugins.PluginImpl {
	ret := _m.Called(_a0)

	var r0 plugins.PluginImpl
	if rf, ok := ret.Get(0).(func(*plugins.Plugin) plugins.PluginImpl); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugins.PluginImpl)
		}
	}

	return r0
}
