// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VaultAPIClient is an autogenerated mock type for the VaultAPIClient type
type VaultAPIClient struct {
	mock.Mock
}

// GetMountPluginName provides a mock function with given fields: path
func (_m *VaultAPIClient) GetMountPluginName(path string) (string, error) {
	ret := _m.Called(path)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlugin provides a mock function with given fields: name
func (_m *VaultAPIClient) GetPlugin(name string) (map[string]interface{}, error) {
	ret := _m.Called(name)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPluginDir provides a mock function with given fields:
func (_m *VaultAPIClient) GetPluginDir() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVaultConfig provides a mock function with given fields:
func (_m *VaultAPIClient) GetVaultConfig() (map[string]interface{}, error) {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsMLockDisabled provides a mock function with given fields:
func (_m *VaultAPIClient) IsMLockDisabled() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MountPlugin provides a mock function with given fields: name, path
func (_m *VaultAPIClient) MountPlugin(name string, path string) error {
	ret := _m.Called(name, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadValue provides a mock function with given fields: path
func (_m *VaultAPIClient) ReadValue(path string) (map[string]interface{}, error) {
	ret := _m.Called(path)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterPlugin provides a mock function with given fields: name, command, sha
func (_m *VaultAPIClient) RegisterPlugin(name string, command string, sha string) error {
	ret := _m.Called(name, command, sha)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, command, sha)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReloadPlugin provides a mock function with given fields: name
func (_m *VaultAPIClient) ReloadPlugin(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteValue provides a mock function with given fields: path, value
func (_m *VaultAPIClient) WriteValue(path string, value map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(path, value)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(path, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(path, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
