// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	questions "github.com/opencredo/venafi-vault-wizard/app/questions"
	mock "github.com/stretchr/testify/mock"
)

// Question is an autogenerated mock type for the Question type
type Question struct {
	mock.Mock
}

// Answer provides a mock function with given fields:
func (_m *Question) Answer() questions.Answer {
	ret := _m.Called()

	var r0 questions.Answer
	if rf, ok := ret.Get(0).(func() questions.Answer); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(questions.Answer)
	}

	return r0
}

// Ask provides a mock function with given fields:
func (_m *Question) Ask() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
