// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	questions "github.com/opencredo/venafi-vault-wizard/app/questions"
	mock "github.com/stretchr/testify/mock"
)

// Questioner is an autogenerated mock type for the Questioner type
type Questioner struct {
	mock.Mock
}

// NewClosedQuestion provides a mock function with given fields: question
func (_m *Questioner) NewClosedQuestion(question *questions.ClosedQuestion) questions.Question {
	ret := _m.Called(question)

	var r0 questions.Question
	if rf, ok := ret.Get(0).(func(*questions.ClosedQuestion) questions.Question); ok {
		r0 = rf(question)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(questions.Question)
		}
	}

	return r0
}

// NewOpenEndedQuestion provides a mock function with given fields: question
func (_m *Questioner) NewOpenEndedQuestion(question *questions.OpenEndedQuestion) questions.Question {
	ret := _m.Called(question)

	var r0 questions.Question
	if rf, ok := ret.Get(0).(func(*questions.OpenEndedQuestion) questions.Question); ok {
		r0 = rf(question)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(questions.Question)
		}
	}

	return r0
}
