name: "Venafi Vault Wizard Check"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Lint"
        uses: golangci/golangci-lint-action@v2
      - name: "Format"
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: '-l -d'
  test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v1
      - name: "Set up Go 1.16"
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: "Build"
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: "Test"
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test
